configfile: "pipeline_params.yml"

rule all:
    input:
        "../results/abstract_tsne_clustering.png"

checkpoint list_download:
    output:
        directory("../data/raw/PMIDs/ID_batches")
    shell:
        """
        mkdir -p ../data/raw/PMIDs
        bash 1-ID_list_downl.sh "{config[test]}" "{config[url]}"
        """

rule article_download:
    input:
        "../data/raw/PMIDs/ID_batches/batch_{id}"
    output:
        "../data/raw/Articles/artbatches/batch_{id}.done"
    shell:
        """
        mkdir -p ../data/raw/Articles/artbatches
        mkdir -p ../data/raw/Articles/individual
        bash 2-journal_downl.sh {input}
        touch {output}
        """

rule journal_formatting:
    input:
        "../data/raw/PMIDs/ID_batches",
        lambda wildcards: expand(
            "../data/raw/Articles/artbatches/batch_{id}.done",
            id=glob_wildcards("../data/raw/PMIDs/ID_batches/batch_{id}").id
        )
    output:
        "../data/clean/journal_data_cleaned.tsv"
    
    shell:
        """
        Rscript 3-journal_formatting.R ../data/raw/Articles {output}
        """

rule journal_visualisation:
    input:
        "../data/clean/journal_data_cleaned.tsv"
    output:
        "../results/abstract_tsne_clustering.png"
    shell:
        """
        mkdir -p ../results
        Rscript 4-journal_visualisation.R {output} {config[searchK]} {config[topicnumber]} "{config[test]}"
        """
