configfile: "config.yml"

rule all:
    input:
        "../data/clean/journal_data_cleaned.tsv"


rule list_download:
    output:
        "../data/raw/IDs/IDs.xml"
    shell:
        "bash 1-ID_list_downl.sh {output}"


rule article_download:
    input:
        "../data/raw/IDs/IDs.xml"
    output:
        directory("../data/raw/Articles")
    
    params:
        test=config["test"]
    
    shell:
        """
        mkdir -p ../data/raw/Articles
        bash 2-journal_downl.sh
        """


rule journal_formatting:
    input:
        "../data/raw/Articles"
    output:
        "../data/clean/journal_data_cleaned.tsv"
    shell:
        """
        Rscript 3-journal_formatting.R ../data/raw/Articles {output}
        """
